// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(DxContext))]
    [Migration("20240421223746_RegistrosIniciais")]
    partial class RegistrosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuthToken");
                });

            modelBuilder.Entity("Domain.Model.Beneficiarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("DataNasc")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("Domain.Model.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnosContribuicao")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ConjugeDataNasc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConjugeNome")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataCasamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataPosse")
                        .HasColumnType("longtext");

                    b.Property<string>("DespesaMensal")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmpresaTrabalho")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("longtext");

                    b.Property<string>("Etapa")
                        .HasColumnType("longtext");

                    b.Property<string>("FilhosMaiores")
                        .HasColumnType("longtext");

                    b.Property<string>("Fuma")
                        .HasColumnType("longtext");

                    b.Property<string>("Fumante")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoSeguradora")
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("ImpostoDeRenda")
                        .HasColumnType("longtext");

                    b.Property<string>("MaiorPrioridade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("ObrigacoesFiscaisExterior")
                        .HasColumnType("longtext");

                    b.Property<string>("Ocupacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PoliticamenteExposto")
                        .HasColumnType("longtext");

                    b.Property<string>("PossuiAlgumaAtividade")
                        .HasColumnType("longtext");

                    b.Property<string>("PossuiDeficiencia")
                        .HasColumnType("longtext");

                    b.Property<bool?>("PossuiFilhos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PresidenteNoBrasil")
                        .HasColumnType("longtext");

                    b.Property<string>("ProblemaSaude")
                        .HasColumnType("longtext");

                    b.Property<string>("ProblemasSaude")
                        .HasColumnType("longtext");

                    b.Property<string>("Profissao")
                        .HasColumnType("longtext");

                    b.Property<string>("QuantidadeFilhos")
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeFilhosMaiores")
                        .HasColumnType("int");

                    b.Property<string>("QuantidadeSubstancia")
                        .HasColumnType("longtext");

                    b.Property<string>("RealizouCirurgia")
                        .HasColumnType("longtext");

                    b.Property<string>("RegimeContratacao")
                        .HasColumnType("longtext");

                    b.Property<string>("RendaBruta")
                        .HasColumnType("longtext");

                    b.Property<string>("ReservaEmergencia")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("SofreDoencas")
                        .HasColumnType("longtext");

                    b.Property<string>("TempoReserva")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSubstancia")
                        .HasColumnType("longtext");

                    b.Property<string>("TomaRemedio")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalAplicacoesFinanceiros")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalImoveis")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalVeiculos")
                        .HasColumnType("longtext");

                    b.Property<string>("UsoMedicamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ViagemInternacional")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("Domain.Model.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("Domain.Model.Dados.AdicionalDiariaInternacaoHospitalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AdicionalDiariaInternacaoHospitalar");
                });

            modelBuilder.Entity("Domain.Model.Dados.DiariaIncapacidadeTemporariaAcidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("I13a30")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I31a35")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I36a40")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I41a45")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I46a50")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I51a55")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I56a60")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("I61a65")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InvalidezAcidentalMajorada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MorteAcidental")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RendaMensal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DiariaIncapacidadeTemporariaAcidente");
                });

            modelBuilder.Entity("Domain.Model.Dados.DiariaInternacaoHospitalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("T150")
                        .HasColumnType("double");

                    b.Property<double>("T200")
                        .HasColumnType("double");

                    b.Property<double>("T250")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DiariaInternacaoHospitalar");
                });

            modelBuilder.Entity("Domain.Model.Dados.DitMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("V1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V10")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V11")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V12")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V13")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V14")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V15")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V16")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V17")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V18")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V19")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V20")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V21")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V22")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V23")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V24")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V25")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V26")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V27")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V28")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V29")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V30")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V5")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V6")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V7")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V8")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("V9")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DitMedico");
                });

            modelBuilder.Entity("Domain.Model.Dados.DoencasGraves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Essencial")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Plus")
                        .HasColumnType("double");

                    b.Property<double>("Premium")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DoencasGraves");
                });

            modelBuilder.Entity("Domain.Model.Dados.DoencasGravesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DoencasGravesMaster");
                });

            modelBuilder.Entity("Domain.Model.Dados.InvalidezAcidenteMajorada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("InvalidezAcidenteMajorada");
                });

            modelBuilder.Entity("Domain.Model.Dados.InvalidezAcidenteMajoradaDoenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("InvalidezAcidenteMajoradaDoenca");
                });

            modelBuilder.Entity("Domain.Model.Dados.InvalidezTotalAcidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("InvalidezTotalAcidente");
                });

            modelBuilder.Entity("Domain.Model.Dados.MortePorAcidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("MortePorAcidente");
                });

            modelBuilder.Entity("Domain.Model.Dados.PensaoPorMorte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("I10")
                        .HasColumnType("double");

                    b.Property<double>("I15")
                        .HasColumnType("double");

                    b.Property<double>("I20")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PensaoPorMorte");
                });

            modelBuilder.Entity("Domain.Model.Dados.PrazoCerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("I10")
                        .HasColumnType("double");

                    b.Property<double>("I15")
                        .HasColumnType("double");

                    b.Property<double>("I20")
                        .HasColumnType("double");

                    b.Property<double>("I5")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PrazoCerto");
                });

            modelBuilder.Entity("Domain.Model.Dados.RendaInvalidez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("I20")
                        .HasColumnType("double");

                    b.Property<double>("I30")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RendaInvalidez");
                });

            modelBuilder.Entity("Domain.Model.Dados.SafLuxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Familiar")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Individual")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("SafLuxo");
                });

            modelBuilder.Entity("Domain.Model.Dados.SafSuperLuxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Familiar")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Individual")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("SafSuperLuxo");
                });

            modelBuilder.Entity("Domain.Model.Dados.SafSuperLuxoPorIdade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Familiar")
                        .HasColumnType("double");

                    b.Property<int>("IdadeMaxima")
                        .HasColumnType("int");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<double>("Individual")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("SafSuperLuxoPorIdade");
                });

            modelBuilder.Entity("Domain.Model.Dados.TaxaPrevcom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Invalidez")
                        .HasColumnType("double");

                    b.Property<double>("Morte")
                        .HasColumnType("double");

                    b.Property<double>("PercentualReajusteInvalidez")
                        .HasColumnType("double");

                    b.Property<double>("PercentualReajusteMorte")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("TaxaPrevcom");
                });

            modelBuilder.Entity("Domain.Model.Dados.TermLife", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Feminino10")
                        .HasColumnType("double");

                    b.Property<double>("Feminino15")
                        .HasColumnType("double");

                    b.Property<double>("Feminino20")
                        .HasColumnType("double");

                    b.Property<double>("Feminino25")
                        .HasColumnType("double");

                    b.Property<double>("Feminino30")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Masculino10")
                        .HasColumnType("double");

                    b.Property<double>("Masculino15")
                        .HasColumnType("double");

                    b.Property<double>("Masculino20")
                        .HasColumnType("double");

                    b.Property<double>("Masculino25")
                        .HasColumnType("double");

                    b.Property<double>("Masculino30")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("TermLife");
                });

            modelBuilder.Entity("Domain.Model.Dados.VidaInteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Homem")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Mulher")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("VidaInteira");
                });

            modelBuilder.Entity("Domain.Model.Dados.VidaInteiraConjuge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<double>("Homem")
                        .HasColumnType("double");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Mulher")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("VidaInteiraConjuge");
                });

            modelBuilder.Entity("Domain.Model.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("OrgaoExpedidor")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Domain.Model.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("Logadouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Domain.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAlteracao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataCriacao"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Permissao")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
